import {freshState,start,move,pause,update} from './model.mjs';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
let saved=0;try{saved=Number(localStorage.getItem('ashifrza-commit-dash-best'))||0;}catch{}
const s=freshState(saved);let last=0,feedbackUntil=0,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function motionUI(){$('motion').setAttribute('aria-pressed',String(reduced));$('motion').textContent=reduced?'Motion reduced':'Reduce motion';}motionUI();
function resize(){const r=canvas.getBoundingClientRect();canvas.width=Math.round(r.width*Math.min(devicePixelRatio,2));canvas.height=Math.round(r.height*Math.min(devicePixelRatio,2));}new ResizeObserver(resize).observe(canvas);
function project(lane,z){const depth=Math.pow(Math.max(0,z),1.65),spread=32+depth*250;return {x:480+(lane-1)*spread,y:110+depth*325,scale:.15+depth*.95};}
function poly(points,fill,stroke){ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function cube(x,y,size,color){poly([[x,y-size],[x+size,y-size*.5],[x,y],[x-size,y-size*.5]],color);poly([[x-size,y-size*.5],[x,y],[x,y+size],[x-size,y+size*.5]],'#112b3d',color);poly([[x,y],[x+size,y-size*.5],[x+size,y+size*.5],[x,y+size]],'#1a3f52',color);}
function draw(now){ctx.setTransform(canvas.width/960,0,0,canvas.height/490,0,0);ctx.fillStyle='#090f1b';ctx.fillRect(0,0,960,490);const glow=ctx.createRadialGradient(480,110,0,480,110,400);glow.addColorStop(0,'#183859');glow.addColorStop(1,'#090f1b');ctx.fillStyle=glow;ctx.fillRect(0,0,960,490);ctx.lineWidth=1;
 ctx.strokeStyle='#29445f';for(let i=0;i<4;i++){const top=480+(i-1.5)*32,bottom=480+(i-1.5)*280;ctx.beginPath();ctx.moveTo(top,110);ctx.lineTo(bottom,490);ctx.stroke();}
 for(let i=0;i<15;i++){const z=(i/15+(!reduced&&s.mode==='running'?s.time*.16:0))%1,p=project(1,z),half=48+Math.pow(z,1.65)*435;ctx.globalAlpha=.2+z*.5;ctx.beginPath();ctx.moveTo(480-half,p.y);ctx.lineTo(480+half,p.y);ctx.stroke();}ctx.globalAlpha=1;
 ctx.font='10px Consolas,monospace';ctx.textAlign='center';ctx.fillStyle='#6583a2';ctx.fillText('DEPLOYMENT HORIZON',480,85);
 for(const o of [...s.objects].sort((a,b)=>a.z-b.z)){if(o.done)continue;const p=project(o.lane,o.z);cube(p.x,p.y,22*p.scale,o.kind==='commit'?'#62e7ff':'#ff728b');if(p.scale>.5){ctx.fillStyle='#edf5ff';ctx.font=`bold ${16*p.scale}px Consolas`;ctx.fillText(o.kind==='commit'?'+':'!',p.x,p.y-2*p.scale);}}
 const p=project(s.lane,1);ctx.shadowBlur=reduced?0:20;ctx.shadowColor='#af98ff';poly([[p.x,412],[p.x+32,444],[p.x,435],[p.x-32,444]],'#af98ff','#e1d5ff');ctx.shadowBlur=0;
 for(let i=0;i<3;i++){ctx.fillStyle=s.lane===i?'#af98ff':'#263650';ctx.fillRect(465+i*12,466,7,3);}if(now>feedbackUntil)$('feedback').textContent='';}
function sync(){for(const [id,val]of Object.entries({score:String(s.score).padStart(4,'0'),lives:`${s.lives} / 3`,time:Math.max(0,45-s.time).toFixed(1),best:String(s.best).padStart(4,'0')}))$(id).textContent=val;$('pause').disabled=!['running','paused'].includes(s.mode);$('pause').textContent=s.mode==='paused'?'▶':'Ⅱ';$('pause').setAttribute('aria-label',s.mode==='paused'?'Resume game':'Pause game');}
function screen(){const active=s.mode==='running';$('overlay').hidden=active;if(active)return;const cfg=s.mode==='paused'?['BUILD PAUSED','Take a breath.','Your run is waiting.','RESUME RUN']:s.mode==='won'?['DEPLOYMENT SUCCESS','You shipped it.',`${s.score} points. Best in this browser: ${s.best}.`,'PLAY AGAIN']:s.mode==='over'?['BUILD FAILED','Bugs happen.',`${s.score} points. Fix, restart, repeat.`,'TRY AGAIN']:['READY TO DEPLOY?','One run.<br>Zero excuses.','Cyan cubes are commits. Red cubes are bugs.<br>Collect 5 in a row for double points.','START RUN'];$('status-label').textContent=cfg[0];$('status-title').innerHTML=cfg[1];$('status-copy').innerHTML=cfg[2];$('start').innerHTML=cfg[3]+' <span>↗</span>';$('announcement').textContent=cfg[0]+' '+s.score+' points.';}
function begin(){if(s.mode==='paused')pause(s);else start(s);last=performance.now();screen();sync();canvas.focus({preventScroll:true});}
function togglePause(){pause(s);screen();sync();}
$('start').onclick=begin;$('pause').onclick=togglePause;$('left').onclick=()=>move(s,-1);$('right').onclick=()=>move(s,1);$('motion').onclick=()=>{reduced=!reduced;motionUI();};
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight',' ','a','A','d','D','Escape'].includes(e.key)){if(e.target.tagName==='BUTTON'&&e.key===' ')return;e.preventDefault();if(e.repeat&&[' ','Escape'].includes(e.key))return;if(['ArrowLeft','a','A'].includes(e.key))move(s,-1);if(['ArrowRight','d','D'].includes(e.key))move(s,1);if(e.key===' '){if(['ready','over','won'].includes(s.mode))begin();else togglePause();}if(e.key==='Escape'&&['running','paused'].includes(s.mode))togglePause();}});
let touchX=0;canvas.addEventListener('pointerdown',e=>{touchX=e.clientX;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointerup',e=>{if(Math.abs(e.clientX-touchX)>20)move(s,e.clientX>touchX?1:-1);});
window.addEventListener('blur',()=>{if(s.mode==='running')togglePause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&s.mode==='running')togglePause();});
function tick(now){const dt=last?(now-last)/1000:0;last=now;const before=s.mode;const events=update(s,dt);if(events.includes('commit')||events.includes('bug')){$('feedback').textContent=events.includes('bug')?'BUG HIT / -1 HEALTH':s.combo>=5?'COMBO / +20':'COMMIT / +10';$('feedback').style.color=events.includes('bug')?'#ff728b':'#62e7ff';feedbackUntil=now+650;}if(before!==s.mode){try{localStorage.setItem('ashifrza-commit-dash-best',String(s.best));}catch{}screen();}draw(now);sync();requestAnimationFrame(tick);}screen();sync();requestAnimationFrame(tick);
